### ISSUE TITLE
Production build leaves *.deptree.js files from optimization step in www/build directory

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic-app-scripts#1104]
#### Short description of the problem:
Production build leaves *.deptree.js files from optimization step in www/build directory which increases the final app size quite a bit.

#### What behavior are you expecting?
The deptree files should be removed like the source map files.

**Steps to reproduce:**
1. ionic cordova build ios --prod
2. check www/build directory

**Which @ionic/app-scripts version are you using?**
2.0.1

**Comment by peterpeterparker** [comment]
same:

    BUILD SUCCESSFUL
    
    Total time: 20.436 secs
    Built the following apk(s):
    
     /Users/me/Documents/projects/proj/platforms/android/build/outputs/apk/android-debug.apk
     mbp-de-me-2:proj me$ cd www/build/
     mbp-de-me-2:proj me$ ls -ltr
    total 24416
    -rw-r--r--  1 me  staff    15793 13 jul 07:26 sw-toolbox.js
    -rw-r--r--  1 me  staff    89629 13 jul 07:26 polyfills.js
    -rw-r--r--  1 me  staff  9601212 13 jul 07:26 deptree.js
    -rw-r--r--  1 me  staff   595027 13 jul 07:28 main.css
    -rw-r--r--  1 me  staff  1049246 13 jul 07:28 main.js
    -rw-r--r--  1 me  staff  1138359 13 jul 07:28 vendor.js

**Comment by JoeMeeks** [comment]
@danbucholtz per the App-Scripts 2.0.0 release notes:
> This means that src/index.html must be modified to include a new vendor script tag <script src="build/vendor.js"></script>.

`ionic-app-scripts watch` and `ionic-app-scripts build` do output vendor.js into www/build correctly, however `ionic-app-scripts build --prod` results in vendor.js missing and deptree.js existing in www/build instead.

Should optimzation.config.js output vendor.js instead of deptree.js?
https://github.com/ionic-team/ionic-app-scripts/blob/v2.0.1/config/optimization.config.js

**Comment by danbucholtz** [comment]
This is fixed in `2.0.2`.

Thanks,
Dan
