### ISSUE TITLE
module.ts file missing with 4.0.0

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-app-scripts#1105]
_From @danielehrhardt on July 12, 2017 0:44_

ionic g page name

-->
`C:\Users\Daniel\Desktop\Alles\Projekte\Contacts\contacts-app\src\pages\search-overview\search-overview.ts
            has a @IonicPage decorator, but it does not have a corresponding "NgModule" at
            C:\Users\Daniel\Desktop\Alles\Projekte\Contacts\contacts-app\src\pages\search-overview\search-overview.module.ts`

_Copied from original issue: ionic-team/ionic-cli#2511_

**Comment by mhartington** [comment]
_From @saimon24 on July 12, 2017 5:20_

Yes I can confirm this, latest version is not creating a module file for pages anymore.

**Comment by mhartington** [comment]
This is on purpose. We still need to update the templates before we release 3.5.1 though.

We did this because the base starters are not setup for lazy loading. Which is fine, but when a new user tries to generate a new page, they'll get ngModule and `@IonicPage` right away. Since this can be confusing, we disabled the auto-generation of ngModule for the time being. I hope to have a more interactive setup soon that will prompt the user if they want this page lazy loaded or not.

**Comment by janpio** [comment]
So this is only a temporary problem until 3.5.1 is released which updates the templates (that are used to generate a page) to not include `@IonicPage` any more, right?

**Comment by mhartington** [comment]
Correct

Mike Hartington

**Comment by danielehrhardt** [comment]
Yes, i understand. Thank you for your fast reply on this.

**Comment by tscislo** [comment]
Lazy loading is generally a great feature. My understanding is that right now after 3.5.1 when we do ionic g page the page by default will be added as a non lazy loading page, is that correct? Wouldn't it be better to have it generated with a NgModule and for it to be lazy loaded?

**Comment by worbunkel** [comment]
Would it be valuable to add an option like --lazyload to do the lazy load on generate for page and tab in the time until it is fully implemented later? It seems like it would ease confusion. Especially for those who are going through up to date tutorials that tell them that a module file will be generated for lazy loading. I would be happy to submit a PR for this if it is desired functionality.

**Comment by janpio** [comment]
Something like that will be implemented. 

This is actually not that easy because three parties are working here: `ionic` (CLI) is running the command, `@ionic/app-scripts` is generating the files that it gets from the templates folder inside `ionic-angular`. Right now there is only one template for a page.

Also you would have to get the starter project working with lazy loaded pages by default to not be in the state from before the change. And that was considered "bad enough" to go back to non-lazy loaded.

**Comment by worbunkel** [comment]
I understand the difficulty. I am willing to go through the effort. It's a way for me to get my feet wet in the source anyway.

I do not understand the last thing you mentioned. The starter projects would not change. They would still work if someone did ionic g without the --lazyload option. It seems intuitive to me that if a new user uses the --lazyload option without knowledge of how lazyload works, then that user should expect to have to do some research on it.

**Comment by orouwk** [comment]
yesterday i was scared when starting a new project in a hurry realized that the lazy loading is not generated by default in cli. First thought i had was that lazy loading was removed due to the issues it has, and that was scary enough.
I tried to quickly  find a reference on this topic and realized that i was not aware of a place where important architecture decisions on ionic 2-3 is available.
I might be wrong and I hope there is one. Maybe someone can help with a link to it, if is not so visible on the main website/git.

**Comment by mhartington** [comment]
Just to comment on this again, We will be adding the functionality back.
Since the default starter templates were not lazy loaded, generating a new page that was lazy loaded ended up causing issues out of the box. Since most users were not using lazy loading out of the box, the temporary removal of this addressed this.

When we add the functionality back, there will be a new prompt asking devs if they want the page to be lazy loaded. 

As far as looking for architecture decisions, I wrote about these on the ionic blog.
http://blog.ionic.io/ionic-and-lazy-loading-pt-2/

**Comment by mhartington** [comment]
Closing for now.
