### ISSUE TITLE
The package appears to be currupted

### ISSUE THREAD

**Issue by kaito-kaito** [ionic-team/ionic-app-scripts#1272]
Hi there
I'm trying to build my app with a release version but when I install it it always gives me (The package appears to be currupted)
I also tried to create a new app and then build it with release and prod, the problem still the same.
But with debug version it works fine.
I tried to use both release and prod.
I tried to install it in different device.
All attempts failed
Hope you can help me
Thank you

**Comment by danbucholtz** [comment]
Hi @kaito-kaito,

I'm not sure what you mean. Can you run the following commands and try again? They may require sudo:

```
npm install -g ionic@latest
npm install -g cordova@latest
```

If this does not resolve your issue, please visit the [Ionic Support Forum](https://forum.ionicframework.com/) and post your question there. We try to avoid questions in our issues list since we work off this list to fix bugs.

Thanks,
Dan
