### ISSUE TITLE
Typescript support for service worker and web workers

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionic-app-scripts#499]
"How can I write a service worker or web worker in TypeScript and have the script compile and copy to www?"

Thanks,
Dan

**Comment by thielCole** [comment]
@danbucholtz have you heard about this? I was thinking about trying to run my angular ui as a background web worker which would require this to happen. Maybe there is a way to write a custom config file.

**Comment by thielCole** [comment]
@danbucholtz with the release of [angular 4.3](https://twitter.com/IgorMinar/status/874432441288540161), they are releasing full support for service workers, and in particular, I think having the Angular UI run in a service worker could be a big asset to Ionic in terms of performance improvements. 

[Bootstrap Angular UI with Webpack](https://stackoverflow.com/questions/43276044/angular-cli-generated-app-with-web-workers)

**Comment by danbucholtz** [comment]
@thielCole,

We probably will do something with the service worker in the future but for now we're not overly concerned about it. We would likely integrate a library to make things simple.

Thanks,
Dan

**Comment by mjosephd** [comment]
@danbucholtz we are using webworkers in our ionic app to do some calculation and processing related things, since the ionic team is busy could you point us in the right direction. This may be in the form of a workaround or some pointers on where to modify the ionic app scripts, we are using version 1.0.0 currently and are ok to maintain our own version of ionic app scripts until this is officially supported as well.
