### ISSUE TITLE
Ionic Run Android -c -l does not work

### ISSUE THREAD

**Issue by HexagonStorms** [ionic-team/ionic-app-scripts#991]
#### Short description of the problem:
Running `ionic run android` works perfectly, but running with ```ionic run android -consolelogs -livereload``` does not work.

#### What behavior are you expecting?
Whenever I attempt to run ```ionic run android -c -l``` I receive an “the connection to the server was unsuccessful http://192.168.20.1.8100).” after the application loads.

I believe the application exists on a different server when I run the following command, but I have no idea how to retrieve the correct server, or why it is not pulling the correct server by default.

I have a virtual machine on my computer. I always halt it in order for this application to work. It used to work when I ran ```ionic run android -c -l -address="192.168.20.232"``` but that has stopped working. 

**Steps to reproduce:**
1. Run ```ionic run android -consolelogs -livereload``` in the command line. 

I do receive a LAUNCH SUCCESS every time. The application Splashscreen also appears, and then the application crashes with the following error. 
https://guides.github.com/features/mastering-markdown/
the connection to the server was unsuccessful http://192.168.20.1.8100).

**Which @ionic/app-scripts version are you using?**
1.3.7

**Other information:**
This issue is very similar to https://github.com/driftyco/ionic-app-scripts/issues/473, but that solution does not work for me.

**Comment by cocowalla** [comment]
Are you running McAfee HIPS, or some other firewall system, which might block incoming traffic?

If so, you need to set an exception for ports 8100, 35729 and 53703 - this worked for me.

**Comment by HexagonStorms** [comment]
I am confirm that I am not running any firewall system on my Mac.

**Comment by HexagonStorms** [comment]
Just leaving a comment that I have now updated my ionic application to Ionic 3. I just checked to see if this issue still exists and it does.

**Comment by pojda** [comment]
@HexagonStorms I spent a LOT of time figuring this out and finally managed to get it working!

The thing is, even tho the firewall was deactivated in System Preferences it still had something up. I found a link to completely disable it: https://coderwall.com/p/zt8aqa/disable-mac-osx-firewall-from-command-line

But in order to do it, you'll have to reboot and disable Apple's SIP.: https://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-macos-os-x

So:

1. Reboot&Disable SIP
2. Boot normally again and run: 
`sudo launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist`
3. Now run your `ionic cordova run android -lc` and be happy :)
